# Generated by Django 5.1.1 on 2024-09-25 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_table",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(null=True)),
                ("last_name", models.CharField(null=True)),
                ("gender", models.IntegerField(null=True)),
                ("nationality", models.CharField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone", models.CharField(null=True)),
                ("country_code", models.CharField(null=True)),
                ("user_type", models.IntegerField(null=True)),
                ("created_by", models.IntegerField(null=True)),
                ("created_time", models.DateTimeField(null=True)),
                ("modified_by", models.IntegerField(null=True)),
                ("modified_time", models.DateTimeField(null=True)),
                ("hidden", models.BooleanField(null=True)),
            ],
        ),
    ]
