# Generated by Django 5.1.1 on 2024-09-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                ("gender", models.IntegerField()),
                ("nationality", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField()),
                ("country_code", models.CharField()),
                ("user_type", models.IntegerField()),
                ("created_by", models.IntegerField()),
                ("created_time", models.DateTimeField()),
                ("modified_by", models.IntegerField()),
                ("modified_time", models.DateTimeField()),
                ("hidden", models.BooleanField()),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
