# Generated by Django 5.1.1 on 2024-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finder", "0002_alter_user_table_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_table",
            name="password_hash",
            field=models.CharField(null=True),
        ),
    ]
