# Generated by Django 5.1.1 on 2024-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finder", "0003_user_table_password_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="LookupTable",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("master_key", models.CharField()),
                ("key", models.CharField()),
                ("value", models.IntegerField()),
            ],
        ),
    ]
