# Generated by Django 5.1.1 on 2024-10-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finder", "0005_alter_lookuptable_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_table",
            name="created_by",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="user_table",
            name="modified_by",
            field=models.CharField(null=True),
        ),
    ]
